#!/bin/bash

source /home/alireza/Desktop/Work/Codes/GrainsGPU/Env/grainsGPU.env.sh

# Input file
if [ $1 ]
  then
    ROOT_FILE=$1
  else
    ROOT_FILE=Grains/Init/B1_N1
fi
INPUT_FILE=$ROOT_FILE.xml

#Execute Grains
if [ -f $INPUT_FILE ]
  then
    time ${GRAINS_HOME}/Main/bin${GRAINS_FULL_EXT}/grains $INPUT_FILE
  else
    echo 'Input file' $INPUT_FILE 'does not exist'
fi
